const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const crypto = require('node:crypto');
const { once } = require('node:events');
const { createApp } = require('../server');
const { createStore } = require('../lib/store');
const { solarEstimate } = require('../lib/solar');
const { phoneDigits, validPhone, csvCell, safeWebsite, readTracking, normalizeLead } = require('../lib/domain');
const password='senha-exclusiva-de-teste-12345';
const baseCapture={nome:'Contato de teste',whatsapp:'47987654321',cidade:'Joinville',propertyType:'comercial',conta:700,consentimento:true};
function temporary(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'estrutura-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
async function serverFor(t,options={}){
 const dir=temporary(t),app=createApp({dataDir:dir,password,production:false,preview:false,trustProxy:0,...options});
 const server=app.listen(0,'127.0.0.1');await once(server,'listening');
 t.after(async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));});
 const base='http://127.0.0.1:'+server.address().port;
 async function call(route,{method='GET',body,headers={}}={}){return fetch(base+route,{method,redirect:'manual',headers:{...(body?{'Content-Type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(5000)});}
 async function login(){const r=await call('/api/login',{method:'POST',body:{senha:password}});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];}
 return {call,login,dir,base};
}

test('Fórmulas legadas preservadas: parâmetros de referência',()=>{
 const l=solarEstimate(500,'residencial');
 assert.equal(l.panels,10);assert.equal(l.systemValue,15000);assert.equal(l.systemKwp,5.5);assert.equal(l.remainingBill,60);assert.equal(l.economyMonth,440);assert.equal(l.financingMonths,72);assert.equal(l.paybackMonths,34.1);
 const expected=Number((15000*.018/(1-Math.pow(1.018,-72))).toFixed(2));assert.equal(l.financingInstallment,expected);
 for(const type of ['residencial','comercial','industrial','rural'])for(const bill of [150,500,700,1000,20000]){const e=solarEstimate(bill,type);assert.equal(e.panels,Math.max(3,Math.round(bill/50)));assert.equal(e.systemValue,e.panels*1500);assert.equal(e.economyMonth,bill-60);}
});
test('Telefone brasileiro: preservar DDD 55 e remover somente o país',()=>{assert.equal(phoneDigits('55 98765-4321'),'55987654321');assert.equal(phoneDigits('+55 (55) 98765-4321'),'55987654321');assert.equal(validPhone('55987654321'),true);assert.equal(validPhone('00000000000'),false);assert.equal(validPhone('11999999999'),false);assert.equal(validPhone('+55 (47) 98765-4321'),true);});
test('Links, parâmetros de origem e CSV tratados com segurança',()=>{assert.equal(safeWebsite('javascript:alert(1)'),'');assert.equal(safeWebsite('https://exemplo.com'),'https://exemplo.com/');assert.equal(safeWebsite('www.exemplo.com'),'https://www.exemplo.com/');assert.ok(csvCell('=SUM(A1)').startsWith('"\''));assert.ok(csvCell(' \t+1').startsWith('"\''));assert.equal(readTracking({utm_source:'instagram',utm_campaign:'solar'}).origem,'Meta Ads');assert.equal(readTracking({gclid:'x'}).origem,'Google Ads');assert.equal(readTracking({referrer:'https://exemplo.com/?email=segredo'}).referrer,'https://exemplo.com');assert.ok(Number.isFinite(normalizeLead({segment:'__proto__',propertyType:'constructor'}).score));});
test('Persistência atômica, backups e proteção contra corrupção',t=>{const dir=temporary(t),store=createStore(dir);assert.deepEqual(store.read(),[]);store.write([{id:'a'}]);store.write([{id:'a',name:'A'}]);assert.equal(store.read()[0].name,'A');assert.ok(fs.existsSync(store.file+'.bak'));assert.equal(fs.readdirSync(path.join(dir,'backups')).length,1);fs.writeFileSync(store.file,'{arquivo-corrompido');assert.throws(()=>store.read(),/Nenhum dado/);assert.throws(()=>store.write([]),/Nenhum dado/);assert.equal(fs.readFileSync(store.file,'utf8'),'{arquivo-corrompido');});
test('Produção recusa senha padrão ou exemplo',()=>{assert.throws(()=>createApp({production:true,password:'estrutura2026'}),/PANEL_SENHA/);assert.throws(()=>createApp({production:true,password:'troque-por-uma-senha-unica-e-longa'}),/PANEL_SENHA/);});

test('Fluxo integrado: captura, painel, edição, exportação e logout',async t=>{
 const {call,login,dir}=await serverFor(t);
 await t.test('Páginas e recursos principais acessíveis',async()=>{for(const route of ['/captar','/login','/assets/site.css','/assets/public.js','/assets/crm.js','/assets/login.js','/favicon.svg','/healthz'])assert.equal((await call(route)).status,200,route);assert.equal((await call('/')).status,302);assert.equal((await call('/api/leads')).status,401);assert.equal((await call('/api/backup')).status,401);});
 await t.test('Configuração pública não expõe regras financeiras ou segredo',async()=>{const d=await(await call('/api/site-config')).json();assert.equal(d.whatsapp,'5547989022728');assert.ok(!JSON.stringify(d).includes(password));assert.ok(!('financingInstallment' in d));});
 await t.test('Formulário exige dados válidos e autorização',async()=>{for(const patch of [{consentimento:false},{whatsapp:'123'},{conta:149},{conta:20001},{propertyType:'constructor'},{cidade:''},{nome:'a'}])assert.equal((await call('/api/capture',{method:'POST',body:{...baseCapture,...patch}})).status,400);});
 const captured=await call('/api/capture',{method:'POST',body:{...baseCapture,tracking:{utm_source:'instagram',utm_campaign:'campanha_teste'}}});assert.equal(captured.status,201);const capture=await captured.json();
 await t.test('Resultado público contém só economia, retorno e parcela; oculta total e painéis',()=>{assert.ok(capture.receipt);assert.equal(capture.summary.contaInformada,700);for(const key of ['economiaAno','economyMonth','panels','systemValue','systemKwp','financingInstallment','paybackMonths','leadId','score'])assert.equal(key in capture,false,key);assert.ok(!JSON.stringify(capture).includes('21000'));assert.deepEqual(Object.keys(capture.estimate).sort(),['economyMonth','economyYear','financingInstallment','financingMonths','paybackMonths'].sort());assert.equal(capture.estimate.economyMonth,640);assert.equal(capture.estimate.financingInstallment,522.67);assert.equal(capture.estimate.paybackMonths,32.8);});
 const cookie=await login(),headers={Cookie:cookie};let leads=await(await call('/api/leads',{headers})).json();assert.equal(leads.length,1);let lead=leads[0],id=lead.id,createdAt=lead.createdAt;
 await t.test('CRM recebe dados, campanha e referência interna',()=>{assert.equal(lead.name,baseCapture.nome);assert.equal(lead.origem,'Meta Ads');assert.equal(lead.campanha,'campanha_teste');assert.equal(lead.systemValue,21000);assert.equal(lead.privacyVersion,'2026-09-v1');});
 await t.test('Sessão antiga derivada da senha não dá acesso',async()=>{const old=crypto.createHash('sha256').update('estrutura-solar-salt::'+password).digest('hex');assert.equal((await call('/api/leads',{headers:{Cookie:'estrutura_auth='+old}})).status,401);});
 await t.test('Etapa, temperatura manual e observações são salvas',async()=>{const r=await call('/api/leads/'+id,{method:'PATCH',headers,body:{status:'negociacao',temperatura:'frio',notes:'Aguardar documentação.',nextContactDate:'2026-10-20'}});assert.equal(r.status,200);const d=await r.json();assert.equal(d.status,'negociacao');assert.equal(d.temperatura,'frio');assert.equal(d.temperaturaManual,true);assert.equal(d.notes,'Aguardar documentação.');});
 await t.test('Reenvio preserva criação, origem, etapa e temperatura manual',async()=>{const r=await call('/api/capture',{method:'POST',body:{...baseCapture,conta:900,propertyType:'industrial',tracking:{utm_source:'google'}}});assert.equal(r.status,201);leads=await(await call('/api/leads',{headers})).json();assert.equal(leads.length,1);lead=leads[0];assert.equal(lead.createdAt,createdAt);assert.equal(lead.origem,'Meta Ads');assert.equal(lead.lastTracking.origem,'Google Ads');assert.equal(lead.temperatura,'frio');assert.equal(lead.status,'negociacao');assert.equal(lead.segmentLabel,'Industrial');assert.equal(lead.notes,'Aguardar documentação.');});
 await t.test('Estado inválido não reinicia o funil; perdido automático é frio',async()=>{assert.equal((await call('/api/leads/'+id,{method:'PATCH',headers,body:{status:'invalido'}})).status,400);const d=await(await call('/api/leads/'+id,{method:'PATCH',headers,body:{status:'perdido',temperatura:'auto',faturaRecebida:true}})).json();assert.equal(d.temperatura,'frio');assert.equal(d.temperaturaManual,false);});
 await t.test('Cadastro manual e rejeição de duplicidade por telefone',async()=>{const r=await call('/api/leads',{method:'POST',headers,body:{name:'=SUM(A1)',city:'Guaramirim',propertyType:'comercial'}});assert.equal(r.status,201);assert.equal((await r.json()).canal,'manual');assert.equal((await call('/api/leads',{method:'POST',headers,body:{name:'Outra pessoa',phone:baseCapture.whatsapp}})).status,409);assert.equal((await call('/api/leads',{method:'POST',headers,body:{name:'Link inseguro',website:'javascript:alert(1)'}})).status,400);});
 await t.test('Filtros e CSV incluem só a seleção; fórmulas neutralizadas',async()=>{const r=await call('/api/export.csv?q=SUM',{headers}),csv=await r.text();assert.equal(r.status,200);assert.ok(csv.includes("\"'=SUM(A1)\""));assert.ok(!csv.includes(baseCapture.nome));const only=await(await call('/api/leads?status=perdido',{headers})).json();assert.equal(only.length,1);});
 await t.test('Backup, métricas e proteção por origem',async()=>{const backup=await(await call('/api/backup',{headers})).json();assert.equal(backup.length,2);assert.equal((await(await call('/api/metrics',{headers})).json()).total,2);const r=await call('/api/leads/'+id,{method:'PATCH',headers:{...headers,Origin:'https://malicioso.example'},body:{name:'modificado'}});assert.equal(r.status,403);});
 await t.test('Excluir requer registro existente e não altera os demais',async()=>{assert.equal((await call('/api/leads/inexistente',{method:'DELETE',headers})).status,404);assert.equal((await call('/api/leads/'+id,{method:'DELETE',headers})).status,200);assert.equal((await(await call('/api/leads',{headers})).json()).length,1);assert.ok(fs.existsSync(path.join(dir,'leads.json.bak')));});
 await t.test('Logout revoga o token no servidor',async()=>{assert.equal((await call('/api/logout',{method:'POST',headers,body:{}})).status,200);assert.equal((await call('/api/leads',{headers})).status,401);});
});

test('Prévia HTTPS permite incorporação sem remover autenticação',async t=>{const {call}=await serverFor(t,{preview:true,trustProxy:1});const r=await call('/api/login',{method:'POST',headers:{Origin:'https://3000-preview.e2b.app','X-Forwarded-Proto':'https','X-Forwarded-Host':'3000-preview.e2b.app'},body:{senha:password}});assert.equal(r.status,200);const cookie=r.headers.get('set-cookie');for(const flag of ['HttpOnly','Secure','SameSite=None','Partitioned'])assert.ok(cookie.includes(flag));assert.equal(r.headers.has('x-frame-options'),false);assert.equal((await call('/api/leads')).status,401);});
test('Login tem limite de tentativas',async t=>{const {call}=await serverFor(t);for(let i=0;i<10;i++)assert.equal((await call('/api/login',{method:'POST',body:{senha:'incorreta'}})).status,401);const r=await call('/api/login',{method:'POST',body:{senha:'incorreta'}});assert.equal(r.status,429);assert.ok(r.headers.get('retry-after'));});
test('Prospecção e CNPJ usam respostas externas simuladas, sem enviar mensagens',async t=>{let externalCalls=0;const fetch=async(url,options)=>{externalCalls++;if(url.includes('overpass'))return new Response(JSON.stringify({elements:[{id:123,type:'node',lat:-26.3,lon:-48.8,tags:{name:'Padaria fictícia de teste',shop:'bakery',phone:'+55 47 98765-4321'}}]}),{status:200});return new Response(JSON.stringify({razao_social:'Empresa fictícia de teste',municipio:'JOINVILLE'}),{status:200});};const {call,login}=await serverFor(t,{fetch});const headers={Cookie:await login()};const body={city:'Joinville',segments:['padaria']};let r=await call('/api/discover',{method:'POST',headers,body});assert.equal(r.status,200);const d=await r.json();assert.equal(d.results.length,1);assert.equal(d.results[0].phone,'47987654321');await call('/api/discover',{method:'POST',headers,body});assert.equal(externalCalls,1);r=await call('/api/cnpj/12345678000199',{headers});assert.equal(r.status,200);assert.equal((await r.json()).razao_social,'Empresa fictícia de teste');assert.equal(externalCalls,2);});
